### PR TITLE
Update package.json

### PR DESCRIPTION
**Pull request by Justme764**
Add homepage field to package.json  issue #16

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @Justme764 Sorry I missed replying to this one. You edited the right file but added `homepage` as part of the `repository`. Can you modify it and add it outside ? You can refer to other projects package.json [here](https://github.com/DAVFoundation/xplore/blob/master/package.json#L12) for reference.

**Comment by Justme764** [comment]
ahhh I see what I did.   will fix soon.  having a blizzard here right now.  need to take care of few things.

**Comment by Justme764** [comment]
oh and @cg-cnu  what type of issues would I move on to next to continue learning and get coding?  thanks also how do you run tests?  is there a tutorial for that?

**Comment by cg-cnu** [comment]
oh sorry to hear that @Justme764, you stay safe. Regarding the issue, you can take care of it once things are better. 

I have a two notes for you. The `homepage` field you added to a  json file. Following the `JSON` syntax you need to add a `,` at the end of the line. Your code editor should have notified it while editing. What code editor you are using. And try to read up on `JSON` specification and importance of `package.json` file in a node project. 

And there has been an update to the master branch after you forked. That means you are on older code. You need to update your local clone to the latest upstream which is `https://github.com/DAVFoundation/community-client/` before doing a git push again.

**Comment by Justme764** [comment]
@cg-cnu  I have a conflict.  could you help me decode it?  this is where i need help.  I can change and add but don't know how to decipher the conflict.  Thanks.  I did compare the 2 code file yours and mine and I seem to be missing a lines so maybe I need to update my files with recent merges? but really what to learn how to understand a conflict.  thanks

**Comment by Justme764** [comment]
I'm closing PR so I can get the latest updates.  I think this is how I do it anyhow.  please correct me if I'm wrong. :-)

**Pull request closed without merging**
