### PR TITLE
Add description and repo to package.json

### PR DESCRIPTION
**Pull request by jj-owens**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jj-owens** [comment]
Merge request to resolve issue #5 .

**Comment by cg-cnu** [comment]
Hey @jj-owens Thanks for your contribution 💯 Its looking good. 
Just a minor nitpicking 😄 Would you mind doing one more commit fixing the formatting on the git repo ? 

Right now its looks like this

```
"repository" :
     { "type" : "git",
      "url" : "https://github.com/DAVFoundation/community-client"
    },
```

it needs to look like this
```
"repository" :{ 
      "type" : "git",
      "url" : "https://github.com/DAVFoundation/community-client"
    },
```
Its a minor formatting issue. You just need to move the braces up and do a commit. The pr will automatically get updated. Let me know if you have any questions 🙂

**Comment by jj-owens** [comment]
@cg-cnu sure, no problem!  :)

**Comment by jj-owens** [comment]
Thank you!

**Pull request merged**
