### PR TITLE
updating package.json 

### PR DESCRIPTION
**Pull request by Justme764**
removing section I accidentally copied and pasted from another file and fixing my conflict. well, i hope anyhow

## Description

"homepage": "https://github.com/DAVFoundation/community-client#readme", with , comma this time.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by Justme764** [comment]
Updated package.json with home page and fixed conflict, i think.

**Comment by cg-cnu** [comment]
Hey @Justme764 In the updated pull request you removed the bugs field and added the homepage.
You can see it in the diff [here](https://github.com/DAVFoundation/community-client/pull/22/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2).

Since you are getting used to git and github and how to make contribution to opensource projects, It might be a little overwhelming. I would definitely want you to make this contribution. So, lets talk over in the our contributors channel and clarify where its confusing for you and how we can fix it 🙂

**Comment by Justme764** [comment]
@cg-cnu  the problem is that I donr't have the latest files.  I have deleted the repo and still and re forked and cloned and still don't have the updated files.  I might not have deleted everything properly or I have another local copy on github and not just me pc.  When I added the home page I copied from another file and thought I accidentally added the bug field since I don't have the latest files.  I will either add the bug field back or work on figuring our why my files won't update.  I know this is the problem.  What code editor should I use?  I just hit the pencil.  Thanks

**Comment by Justme764** [comment]
@cg-cnu  I hope the latest pull works.  I also see in the history updates that one of mine says Justme and all the rest say justme 764.  maybe this is why my files are not updating.

**Comment by TalAter** [comment]
Thank you @Justme764 

Apart from a little formatting error (missing indentation) which I fixed, it looks great. 👍 

Congrats on joining the open source world.

**Pull request merged**
